Ex 11
Nickollay/Thinknetika_Test_Guru pull request #11
Opened 2020-11-04 22:04 UTC by Nickollay

2020-11-05 17:45 UTC, VidgarVii requested changes

2020-11-05 17:45 UTC, VidgarVii commented on config/locales/devise.en.yml
> +en:
локаль не до настроена. У тебя по умолчанию стоит ру. Но ты используешь только en.
Так же тут не корректная вложенность. Смотри на название ошибки

2020-11-05 17:45 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    admin_tests_path
тут нужна проверка кто пришел. В данном случаи даже если это был не админ, то его всё ровно отправляют на панель админа. Далее в Admin::BaseController проверяют, что пришел не админ и его редиректят на root_path
В общем тут редирект не очень хорошо. Нужна проверка

2020-11-05 17:50 UTC, VidgarVii requested changes

2020-11-05 17:50 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +      redirect_to [:admin, @answer]
лучше использовать урл хелперы c _path.
В данном случаи получиться admin_answer_path(answer)

2020-11-05 17:55 UTC, VidgarVii requested changes

2020-11-05 17:55 UTC, VidgarVii commented on app/views/devise/registrations/new.html.erb
> +    <%= f.email_field :first_name, autofocus: true, autocomplete: "first name" %>
email_field тут явно лишний)

2020-11-05 17:58 UTC, VidgarVii requested changes

2020-11-05 17:58 UTC, VidgarVii commented on app/views/devise/registrations/new.html.erb
> +    <%= f.email_field :last_name, autofocus: true, autocomplete: "last_name" %>
email_field

2020-11-05 22:23 UTC, Nickollay commented on app/controllers/application_controller.rb
> +    admin_tests_path
done

2020-11-05 22:45 UTC, Nickollay commented on app/controllers/admin/answers_controller.rb
> +      redirect_to [:admin, @answer]
done

2020-11-05 23:14 UTC, Nickollay commented on app/views/devise/registrations/new.html.erb
> +    <%= f.email_field :first_name, autofocus: true, autocomplete: "first name" %>
+

2020-11-05 23:14 UTC, Nickollay commented on app/views/devise/registrations/new.html.erb
> +    <%= f.email_field :last_name, autofocus: true, autocomplete: "last_name" %>
done

2020-11-05 23:20 UTC, Nickollay commented on config/locales/devise.en.yml
> +en:
Сделал пока только для Девайса

2020-11-06 05:36 UTC, VidgarVii requested changes

2020-11-06 05:36 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  end
1 Решение не в бровь, а в глаз) Таким манки патчингом ты полностью убил реализацию метода от after_sign_in_path_for от devise. Если посмотреть его исходник, этот метод довольно-таки полезный. https://github.com/heartcombo/devise/blob/master/lib/devise/controllers/helpers.rb#L215. Выше даже есть дока. И как его использовать. Вспомни метод super.
Получается логика, Если пришол админ, то шлем его в админку, иначе супер

2 Добавляя от сюда отправку флеш сообщения мы делаем метод грязным. И это нарушения принципа единственной ответственности. Опять читаем доку по этому методу.  The default url to be used after signing in. Т.е. для приветствия нам этот метод не подходит. До этого мы эти флешки отправляли через контроллер. Можно этим воспользоваться. Т.е. тебе нужен контроллер, который создаёт сессию, и его не много допилить под себя. Так же используя  полиморфизм. https://github.com/heartcombo/devise/blob/master/app/controllers/devise/sessions_controller.rb

2020-11-06 05:36 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  end
не очень хорошо читается.
```
    return admin_tests_path if current_user.is_a?(Admin)

    root_path
```
так на много лучше 
```
if current_user.admin?
  admin_tests_path
else
  root_path
end
```
или для любителя тернарников
```
current_user.admin? ? admin_tests_path : root_path
```

2020-11-06 20:51 UTC, Nickollay commented on app/controllers/application_controller.rb
> +  end
> 2 Добавляя от сюда отправку флеш сообщения мы делаем метод грязным. И это нарушения принципа единственной ответственности. Опять читаем доку по этому методу. The default url to be used after signing in. Т.е. для приветствия нам этот метод не подходит. До этого мы эти флешки отправляли через контроллер. Можно этим воспользоваться. Т.е. тебе нужен контроллер, который создаёт сессию, и его не много допилить под себя. Так же используя полиморфизм. https://github.com/heartcombo/devise/blob/master/app/controllers/devise/sessions_controller.rb

Про полиморфизм не понял, что имеется ввиду(

Сделал путем переписывания метода `session#create` полностью, все работает.

Но есть вопрос, хотел добавить только сетап флеша и использовать `super`, но выдает ошибку((
Получается, что здесь только полным копированием метода можно решить? или еще есть варианты?
![Screenshot_20201106_234111](https://user-images.githubusercontent.com/38377768/98413380-94441e80-208a-11eb-8f1d-398fdd448f81.png)

2020-11-15 16:25 UTC, merged