Ex 14
Nickollay/Thinknetika_Test_Guru pull request #23
Opened 2021-05-20 17:16 UTC by Nickollay

2021-05-22 12:38 UTC, VidgarVii requested changes

2021-05-22 12:38 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Gist это модель. Значит согласно rails way для записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2021-05-22 12:38 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  end
Можно сильно сократить написав
```
Gist.new(options).save
```

2021-05-22 12:38 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  end
эта логика должна быть внутри сервиса. Не хорошо логикой мучать контроллер. Контроллер должен только делегировать задачи. Сам он почти ни чего не делает

https://ru.wikipedia.org/wiki/GRASP#3._%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80_(Controller)

2021-05-22 12:38 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    response = GistQuestionService.new(@current_question).call
метод call должен вернуть такой объект, который будет содержать в себе только нужные данные для дальнейшей работы. Тут поможет Struct

Так же для сервисов (так как не планируется порождать много объектов) принято убирать конструктор. Т.е. обращение будет таким
```
result = GistQuestionService.call(user: current_user, questio: @passed_test.current_question)

class GistQuestionService
  def self.call(...)
    new(...).perform
  end

  def perform
    ...
``` 

Хорошо бы так же дать название сервису такое, чтобы было понятно что он делает, без изучение кода данного сервиса

2021-05-22 12:38 UTC, VidgarVii commented on app/helpers/gists_helper.rb
> +    link_to gist.url.split('/').last, gist.url
кстати хеш можно получить из респонса создания гиста в гитхаб

2021-05-22 12:38 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    ([@question.body] + @question.answers.pluck(:body)).join("\n")
[@question.body, *@question.answers.pluck(:body)].join("\n")

2021-05-22 12:38 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    GitHubClient.new
когда есть октокит GitHubClient тебе не понадобиться

2021-05-23 21:08 UTC, Nickollay commented on app/helpers/gists_helper.rb
> +    link_to gist.url.split('/').last, gist.url
спасибо, не обратил на это внимание.|
Думаю хранить и хеш и урл это дублирование инфы в базе..
т.к. хеш наименьшая значимая единица из которой можно создать урл - теперь сложил ее в базу:)

2021-05-24 05:13 UTC, VidgarVii requested changes

2021-05-24 05:13 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +
лучше записывать Гист тут. И не придется загрязнять окружение представления лишними инстанс переменными

2021-05-24 05:13 UTC, VidgarVii commented on app/services/create_gist_from_question.rb
> +    response&.html_url.present? && response&.id.present?
достаточно проверки на html_url

2021-05-24 05:13 UTC, VidgarVii commented on app/services/create_gist_from_question.rb
> +    Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
лучше писать ENV.fetch('GITHUB_TOKEN')
Если вдруг ключа не будет. то ошибку будет в данном сервисе, а не внутри октокит

2021-05-24 05:13 UTC, VidgarVii commented on app/services/create_gist_from_question.rb
> +  end
для самообразования глянь паттерн и гем Интерактор. Используется часто

2021-05-24 19:14 UTC, Nickollay commented on app/services/create_gist_from_question.rb
> +  end
спасибо, посмотрю..

2021-05-26 05:55 UTC, merged