Add octicon gem
Nickollay/Thinknetika_Test_Guru pull request #25
Opened 2021-05-26 19:56 UTC by Nickollay

2021-05-29 07:29 UTC, VidgarVii requested changes

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +} )
данный файл как и выше на утилиту вообще не похож. Просто набор функций, которые используются тут же.. Хорошо бы объявления и использованы функционала разделять в отдельные файлы.
Если ты хочешь реально создать какую-то утилиту. То тут должны быть созданы инструменты, а использовать их надо в другом месте.

Еще хорошо бы код написать в ООП стиле. Благо JS костыльно но пока хотя бы так это позволяет
Посмотри видео https://vimeo.com/514327459/1717e45651 Я где-то в конце показывал ребятам реализацию задачи проверки пароля.
На классы исправить надо оба файла

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +
const testTitle1 =
const testTitle2 =

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +function compareRowsAsc(row1, row2) {
уже давно актуален более лучший и безопасней синтаксис это стрелочные функции
```
const compareRowsAsc = (row1, row2) => {
}
```

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +    if (control) { control.addEventListener('click', sortRowsByTitle) }
```
if (control) control.addEventListener('click', sortRowsByTitle)
```

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +} )
простое решение сортировки
https://plnkr.co/edit/vSOTyAmS8sJtH0g0?p=preview&preview

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +    for(let i =0; i < sortedRows.length; i++) {
старайся писать код декларативно.
Тут можно использовать forEach

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +    let parentElementOfTr = sortedTable.querySelectorAll('tr')[1].parentNode
const

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +    let sortedTable = table.cloneNode(true)
const

2021-05-29 07:29 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +    let table = document.querySelector('table'),
const

table очень слабый селектор. Лучше искать по ID, так как он должен быть уникальный
таблиц мб несколько на странице.
Либо взять подходи из css фреймворков. Обращаться к специальным классам, для подключения сортировки

2021-06-06 19:12 UTC, Nickollay commented on app/javascript/utilities/sorting.js
> +} )
На классы переписал. Пробовал разделить класс и вызов класса в разные файлы, но так и не нашел рабочий вариант, при вызове класса JS его не видет (хотя если повесить в файле с классом алерт или лог в него заходит), потратил на это достаточно много времени, но не один мануал, что я видел не дает четких рекомендаций:(
 Сложил в один файл так работает:)

2021-06-07 05:29 UTC, VidgarVii commented on app/javascript/custom/index.js
> +class passwordConfirmation {
не надо класть всё в 1 файл.
1 класс = 1 файл. Название файла = название класса
Использование и подключение утилит в другом файле.

2021-06-14 20:55 UTC, Nickollay commented on app/javascript/custom/index.js
> +class passwordConfirmation {
разбил по файлам в следующем [ПР `ex-16`](https://github.com/Nickollay/Thinknetika_Test_Guru/pull/28)

2021-06-14 20:55 UTC, merged