Ex18 badges
Nickollay/Thinknetika_Test_Guru pull request #60
Opened 2022-10-07 16:13 UTC by Nickollay

2022-10-23 06:52 UTC, VidgarVii requested changes

2022-10-23 06:52 UTC, VidgarVii commented on app/models/rule.rb
> +  scope :without_badge, -> { left_joins(:badge).where(badges: { rule_id: nil } )}
скоупы пишут после валидаций

2022-10-23 06:52 UTC, VidgarVii commented on app/models/category.rb
> +  def name
alias_method.
https://apidock.com/ruby/Module/alias_method

2022-10-23 06:52 UTC, VidgarVii commented on app/services/default_levels_creator.rb
> +  rescue StandardError => e
StandardError надо чинить, а не обрабатывать

2023-03-03 19:00 UTC, Nickollay commented on app/models/category.rb
> +  def name
`alias_method` здесь не работает
<img width="891" alt="Screenshot 2023-03-03 at 21 30 07" src="https://user-images.githubusercontent.com/38377768/222800848-9d80348c-1e55-4d00-8089-bf91b24c1ae7.png">
он не видит `title` тк это не объявленный в модели метод а атрибут таблицы.

Для этого случая отлично сработал `alias_attribute`

2023-03-04 07:04 UTC, VidgarVii requested changes

2023-03-04 07:04 UTC, VidgarVii commented on app/strategies/badges/all_from_category_strategy.rb
> +class Badges::AllFromCategoryStrategy < Badges::InterfaceStrategy
Ошибка называть проверки выдачи баджа Стратегией. Это не тот паттерн

2023-03-05 07:15 UTC, Nickollay commented on app/strategies/badges/all_from_category_strategy.rb
> +class Badges::AllFromCategoryStrategy < Badges::InterfaceStrategy
Возможно 🤔 Я бы сказал что это точно не спецификация, все определения/описания/примеры спецификации,  которые я нашел сводятся к следующему:


> «Спецификация» в программировании — это шаблон проектирования, посредством которого представление правил бизнес логики может быть преобразовано в виде цепочки объектов, связанных операциями булевой логики.

В нашем же случае отсутствует главный признак спецификации - возможность связки правил в цепочки с использованием '**or**' или '**and**' => мы не можем говорить что это спецификация.

В то же время все определения стратегии сводятся к тому что выделяются схожие алгоритмы которые описываются в разных классах и затем в рантайме подставляются, например такое определение:

>  Его задача - выделить схожие алгоритмы, решающие конкретную задачу. Реализация алгоритмов выносится в отдельные классы и предоставляется возможность выбирать алгоритмы во время выполнения программы.

формально это как раз то что реализована - есть набор схожих алгоритмов которые напрямую не взаимодействуют друг с другом и при этом дергаются в рантайме.

Возможно здесь можно подобрать более удачное соответствие какого-либо патерна, я же исходил из того, что главный признак спецификации отсутствует, а в определение стратегии формально вписываемся..

2023-03-05 08:46 UTC, VidgarVii commented on app/strategies/badges/all_from_category_strategy.rb
> +class Badges::AllFromCategoryStrategy < Badges::InterfaceStrategy
Да тут не реализован копозит класс, который бы позволил объединить спецификации используя and и or
И это сделано специально, чтобы не усложнять логику. И оно не требуется в рамках ТЗ. Но при этом именно паттерн Спецификация нужен для ответа удовлетворяет ли объект какой-то бизнес логике.
А Стратегия в таком виде и логике слишком абстрактный паттерн. Да его часто пихают во все щели. Так как он вроде бы подходит. И создаётся еще одна мусорная папка в коде. Как services. Так как в  services можно положить почти все классы манипулирующие с бизнес сущностями

2023-03-06 06:39 UTC, merged