Ex 19 timer
Nickollay/Thinknetika_Test_Guru pull request #62
Opened 2022-10-22 20:18 UTC by Nickollay

2023-03-04 07:18 UTC, VidgarVii requested changes

2023-03-06 14:35 UTC, VidgarVii requested changes

2023-03-06 14:35 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    elsif @test_passage.completed?
Если в коде появляется elsif, то уже можно сказать, что есть проблемы с логикой.
time_over? по сути так же отвечает за завершение теста. Если время вышло, то тест можно считать завершённым.
А для этого уже есть метод .completed?
Стоило бы его улучшить. И не пришлось бы менять код в контроллере

2023-03-06 14:35 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      @rewarded_badges = BadgeRewarder.new.call(@test_passage)
странно. А я не писал, что проверку баджа надо делать только после завершения теста. Данный экшен не отвечает за завершение теста. И её можно обновлять сколько угодно раз и при этом сильно нагружать сервер или получать награды, если есть баг

2023-03-06 14:35 UTC, VidgarVii commented on app/javascript/custom/timer_countdown.js
> +        // location.replace(location.origin + `/test_passages/${test_passage_id}/result`)
не используемый код надо удалять

2023-03-06 14:35 UTC, VidgarVii commented on app/models/test_passage.rb
> +    if seconds > 0
тут тернарник хорошо бы смотрелся
`(seconds > 0) ? seconds : 0`

2023-03-07 05:47 UTC, Nickollay commented on app/controllers/test_passages_controller.rb
> +      @rewarded_badges = BadgeRewarder.new.call(@test_passage)
Возможно где-то было, наверно упустил. Энивей добавил эрли ретерн в `BadgeRewarder`.

2023-03-07 14:48 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    elsif @test_passage.completed?
если время вышло, То логично преположить, что тест завершён!
Успешно или нет - не важно. Это определяет % верно отвеченных вопросов. Тут в любом случаи надо отправлять емэйл с результатом и редиректить юзера на страницу результата. 
Так что если появляется elsif Это всегда проблема в логике

2023-03-09 10:26 UTC, merged